CREATE TABLE [dbo].[WEB_BIOT_RELATION] (
    [BIOTOPE_RELATION_KEY] CHAR(16) NOT NULL PRIMARY KEY,
    [BIOTOPE_KEY] CHAR(16) NOT NULL,
    [RELATED_BIOTOPE_KEY] CHAR(16) NOT NULL,
    [COMMENT] TEXT NULL
	, CONSTRAINT FK_WBR_BIOTOPE_KEY FOREIGN KEY (BIOTOPE_KEY) REFERENCES WEB_BIOTOPE (BIOTOPE_KEY)
	, CONSTRAINT FK_WBR_RELATED_BIOTOPE_KEY FOREIGN KEY (RELATED_BIOTOPE_KEY) REFERENCES WEB_BIOTOPE (BIOTOPE_KEY)
);
