CREATE TABLE [dbo].[WEB_OLD_CODE] (
    [BIOTOPE_KEY] CHAR(16) NOT NULL,
    [OLD_CODE] VARCHAR(255) NOT NULL,
    [VERSION] VARCHAR(20) NULL
	, PRIMARY KEY (BIOTOPE_KEY, OLD_CODE)
	, CONSTRAINT FK_WOC_BIOTOPE_KEY FOREIGN KEY (BIOTOPE_KEY) REFERENCES WEB_BIOTOPE (BIOTOPE_KEY)
);