CREATE TABLE [dbo].[WEB_PHOTO]
(
	[BIOTOPE_KEY] CHAR(16) NOT NULL PRIMARY KEY, 
    [PHOTO_PATH] NTEXT NOT NULL, 
    [PHOTO_CAPTION] NTEXT NULL
	, CONSTRAINT FK_WP_BIOTOPE_KEY FOREIGN KEY (BIOTOPE_KEY) REFERENCES WEB_BIOTOPE (BIOTOPE_KEY)
)
