CREATE TABLE [dbo].[WEB_BIOTOPE_HIERARCHY] (
    [BIOTOPE_KEY] CHAR(16) NOT NULL,
    [BIOTOPE_PARENT_KEY] CHAR(16) NOT NULL,
    [LEVEL] INT NOT NULL,
    [HIGHERLEVEL] INT NOT NULL
	, PRIMARY KEY (BIOTOPE_KEY, BIOTOPE_PARENT_KEY)
	, CONSTRAINT FK_BIOTOPE_KEY FOREIGN KEY (BIOTOPE_KEY) REFERENCES WEB_BIOTOPE (BIOTOPE_KEY)
	, CONSTRAINT FK_BIOTOPE_PARENT_KEY FOREIGN KEY (BIOTOPE_PARENT_KEY) REFERENCES WEB_BIOTOPE (BIOTOPE_KEY)
);