CREATE TABLE [dbo].[WEB_BIOT_SPECIES_GRAB] (
    [BIOTOPE_KEY] CHAR(16) NOT NULL,
    [ITEM_NAME] VARCHAR(100) NOT NULL,
    [FREQ] VARCHAR(10) NULL,
    [ABUND] CHAR(1) NULL,
    [contrib_similarity_STRENGTH] SMALLINT NULL,
    [SED_ABUND_SED_ABUND] INT NULL,
	[RELATIVE_FREQUENCY] SMALLINT NULL,
    [SORT] VARCHAR(255) NULL
	, PRIMARY KEY (BIOTOPE_KEY, ITEM_NAME)
	, CONSTRAINT FK_WBSG_BIOTOPE_KEY FOREIGN KEY (BIOTOPE_KEY) REFERENCES WEB_BIOTOPE (BIOTOPE_KEY)
);