CREATE TABLE [dbo].[WEB_PHOTO]
(
	[ID] int IDENTITY(1,1) PRIMARY KEY,
	[BIOTOPE_KEY] CHAR(16) NOT NULL, 
    [PHOTO_PATH] NTEXT NOT NULL, 
    [PHOTO_CAPTION] NTEXT NULL
	, CONSTRAINT FK_WP_BIOTOPE_KEY FOREIGN KEY (BIOTOPE_KEY) REFERENCES WEB_BIOTOPE (BIOTOPE_KEY)
)
