CREATE TABLE [dbo].[WEB_OLD_CODE] (
    [BIOTOPE_KEY] CHAR(16) NOT NULL,
    [OLD_CODE] VARCHAR(255) NOT NULL,
    [VERSION] VARCHAR(20) NULL,
	[PREVIOUS_FULLNAME] NTEXT NULL, 
    [RELATIONSHIP_TYPE] VARCHAR(255) NULL, 
    [MODIFICATIONS] NTEXT NULL, 
    PRIMARY KEY (BIOTOPE_KEY, OLD_CODE)
	, CONSTRAINT FK_WOC_BIOTOPE_KEY FOREIGN KEY (BIOTOPE_KEY) REFERENCES WEB_BIOTOPE (BIOTOPE_KEY)
);