CREATE TABLE [dbo].[WEB_HABITAT_CORRELATION]
(
	[BIOTOPE_KEY] CHAR(16) NOT NULL, 
    [RELATED_CLASSIFICATION_SYSTEM] VARCHAR(255) NOT NULL, 
    [RELATED_NAME] NVARCHAR(255) NOT NULL, 
    [RELATIONSHIP_TYPE] VARCHAR(255) NOT NULL, 
    [CLASSIFICATION_SYSTEM_URL] NTEXT NULL,
	PRIMARY KEY (BIOTOPE_KEY, RELATED_CLASSIFICATION_SYSTEM, RELATED_NAME)
	, CONSTRAINT FK_WHC_BIOTOPE_KEY FOREIGN KEY (BIOTOPE_KEY) REFERENCES WEB_BIOTOPE (BIOTOPE_KEY)
)
