//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace microservices.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BiotopeDB : DbContext
    {
        public BiotopeDB()
            : base("name=BiotopeDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WEB_BIOT_RELATION> WEB_BIOT_RELATION { get; set; }
        public virtual DbSet<WEB_BIOT_SPECIES_GRAB> WEB_BIOT_SPECIES_GRAB { get; set; }
        public virtual DbSet<WEB_BIOT_SPECIES_OBSERVATION> WEB_BIOT_SPECIES_OBSERVATION { get; set; }
        public virtual DbSet<WEB_BIOTOPE> WEB_BIOTOPE { get; set; }
        public virtual DbSet<WEB_BIOTOPE_HIERARCHY> WEB_BIOTOPE_HIERARCHY { get; set; }
        public virtual DbSet<WEB_HABITAT_CORRELATION> WEB_HABITAT_CORRELATION { get; set; }
        public virtual DbSet<WEB_OLD_CODE> WEB_OLD_CODE { get; set; }
        public virtual DbSet<WEB_PHOTO> WEB_PHOTO { get; set; }
    }
}
