//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace microservices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_BIOTOPE_HIERARCHY
    {
        public string BIOTOPE_KEY { get; set; }
        public string BIOTOPE_PARENT_KEY { get; set; }
        public int LEVEL { get; set; }
        public int HIGHERLEVEL { get; set; }
    
        public virtual WEB_BIOTOPE WEB_BIOTOPE { get; set; }
        public virtual WEB_BIOTOPE WEB_BIOTOPE1 { get; set; }
    }
}
