//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace microservices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_BIOT_SPECIES_OBSERVATION
    {
        public string BIOTOPE_KEY { get; set; }
        public string ITEM_NAME { get; set; }
        public string FREQ { get; set; }
        public string ABUND { get; set; }
        public Nullable<short> contrib_similarity_STRENGTH { get; set; }
        public Nullable<int> SED_ABUND_SED_ABUND { get; set; }
        public string SORT { get; set; }
        public Nullable<short> RELATIVE_FREQUENCY { get; set; }
    
        public virtual WEB_BIOTOPE WEB_BIOTOPE { get; set; }
    }
}
