//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace microservices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_HABITAT_CORRELATION
    {
        public string BIOTOPE_KEY { get; set; }
        public string RELATED_CLASSIFICATION_SYSTEM { get; set; }
        public string RELATED_NAME { get; set; }
        public string RELATIONSHIP_TYPE { get; set; }
        public string CLASSIFICATION_SYSTEM_URL { get; set; }
    
        public virtual WEB_BIOTOPE WEB_BIOTOPE { get; set; }
    }
}
